### ISSUE TITLE
SLIM в RubyMine говорит, что .-modifier плохое имя для класса

### ISSUE THREAD

**Issue by Spirik** [cloudcastle/frontend#7]
Как быть в таком случае?
![image 2015-02-22 at 2 35 15 pm](https://cloud.githubusercontent.com/assets/1061406/6318241/330f656a-ba98-11e4-8878-8936aa90ec90.png)

**Comment by antongunkin** [comment]
Писать `.card(role="link" class="-disabled")` ? :)

**Comment by Spirik** [comment]
Но так же не круто и не удобно( Может, добавлять какой-то префикс для модификаторов, типа `.m-disable`?
